# Generated by Django 4.0.4 on 2022-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_appointment_management_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentdesc',
            field=models.CharField(default='nothing here', max_length=1000),
        ),
    ]
