# Generated by Django 4.0.4 on 2022-04-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_appointment_appointmentdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emailid',
        ),
    ]
