# Generated by Django 4.0.4 on 2022-04-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_rename_documents_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Name',
            new_name='docexp',
        ),
    ]
