# Generated by Django 4.0.4 on 2022-04-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
