# Generated by Django 4.0.4 on 2022-04-29 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0015_update_delete_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('messageis', models.CharField(max_length=1000)),
                ('messageby', models.CharField(max_length=100)),
                ('messageon', models.DateField(default=datetime.datetime(2022, 4, 29, 17, 41, 4, 59393))),
            ],
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
