# Generated by Django 4.0.4 on 2022-05-03 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0016_updatenew_delete_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('specialization', models.CharField(max_length=300)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('current_date', models.DateField()),
                ('current_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='updatenew',
            name='messageon',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 12, 24, 44, 767519)),
        ),
    ]
