# Generated by Django 4.0.4 on 2022-05-03 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0017_doctor_alter_updatenew_messageon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='docdesc',
            field=models.CharField(default='No info available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='updatenew',
            name='messageon',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 12, 44, 25, 321315)),
        ),
    ]
