# Generated by Django 4.0.4 on 2022-05-05 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0020_alter_appointment_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentdate',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 15, 59, 20, 919649)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmenttime',
            field=models.TimeField(default=datetime.datetime(2022, 5, 5, 15, 59, 20, 919649)),
        ),
    ]
