# Generated by Django 4.0.4 on 2022-05-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0023_remove_appointment_dateofapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Management',
        ),
    ]
